ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'

export PATH=$PATH:/usr/local/bin

cd ~/project_node

echo "📦 Pull latest code"
git pull origin main

echo "📦 Install frontend deps"
cd frontapp
npm ci

echo "⚙️ Build Vue"
npm run build

echo "📦 Install backend deps"
cd ../backend
npm install

echo "🚀 Restart server"
pm2 restart app || pm2 start app.js --name app

pm2 save

EOF
